[package]
name = "candle-zencan-adapter"
version = "0.1.1"
edition = "2024"

[dependencies]
tokio = { version = "1.35", default-features = false, features = ["sync"] }
zencan-common = { version = "0.0.3", default-features = false, features = [
	"std",
	"log",
] }
windows = { version = "0.51", features = [
	"Win32_Devices_DeviceAndDriverInstallation",
	"Win32_Devices_Usb",
	"Win32_Foundation",
    "Win32_Security",
	"Win32_Storage_FileSystem",
	"Win32_System_IO",
	"Win32_System_Threading",
] }
